### ISSUE TITLE
[dao] users_dao

### ISSUE THREAD

**Issue by young-k** [cuappdev/fitness-backend#7]
Set up the initial framework for the `dao/` folder, and add `users_dao` with any methods that you think are useful. Document which methods you add, and explain why in a reply to this.

**Comment by sameerkhoja** [comment]
Added users_dao.py which creates methods on top of the users model. The methods I included are:

def get_user_by_id(user_id): This method lets you retrieve a user by it’s ID field.

def get_user_by_email(email):This method lets you retrieve a user by it’s email field.

def is_registered(email): This method tells you whether or not a User with the email address [email] is registered as a user.

def create_user(email, password, first_name='', last_name='')
This method lets you create a User model with the fields [email], [password], [first_name], and [last_name]

**Comment by young-k** [comment]
looks good to me!
